version: '3'

services:
  sonarqube:
    image: sonarqube:latest
    environment:
      - SONARQUBE_JDBC_URL=${SONARQUBE_JDBC_URL}
      - SONARQUBE_JDBC_USERNAME=${SONARQUBE_JDBC_USERNAME}
      - SONARQUBE_JDBC_PASSWORD=${SONARQUBE_JDBC_PASSWORD}
    volumes:
      - sonarqube-data:/sonarqube/data
      - sonarqube-extensions:/sonarqube/extensions
    ports:
      - "9000:9000"

  sonar-postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - sonar-postgres-data:/var/lib/postgresql/data

volumes:
  sonarqube-data:
  sonarqube-extensions:
  sonar-postgres-data: