name: PlatformIO CI/CD & SonarCloud Analysis

on:
  push:
    branches:
      - main
      - src
      - 'releases/**'
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  platformio-ci:
    name: Pipeline PlatformIO
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar PlatformIO
        run: pip install platformio pip-audit

      - name: Comprobar dependencias desactualizadas
        run: pio pkg outdated
      
      - name: Actualizar setuptools
        run: pip install --upgrade setuptools

      - name: Auditar
        run: pip-audit

      - name: Compilar con PlatformIO (generar .cpp para Cppcheck)
        run: pio run --environment esp32thing

      - name: Ejecutar Cppcheck en el entorno
        run: cppcheck --enable=all --error-exitcode=0 src/ || true

      - name: Aplicar correcciones automáticas con Clang-Tidy
        run: pio check --environment esp32thing --skip-packages --flags="--fix-errors --system-headers" || true

  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17  
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        with:
          args: >
            -Dsonar.organization=hub-of-things-1
            -Dsonar.projectKey=hub-of-things_mqtt-dht22 
            -Dsonar.host.url=https://sonarcloud.io/
            -Dsonar.projectName=mqtt-dht22
            -Dsonar.sources="src,include,lib,test"
            -Dsonar.exclusions="**/node_modules/**,**/.pio/**,**/.platformio/**,**/build/**,**/output/**"
            -Dsonar.branch.name=main
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
