name: PlatformIO CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-dependencies:
    name: Verificaci칩n de Dependencias PlatformIO
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: "x64"

      - name: Instalar PlatformIO
        run: pip install platformio

      - name: Comprobar dependencias desactualizadas
        run: pio pkg outdated

  static-analysis:
    name: An치lisis Est치tico de C칩digo
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: "x64"

      - name: Instalar PlatformIO
        run: pip install platformio

      - name: Ejecutar Cppcheck
        run: pio check --skip-packages --fail-on-defect high

      - name: Ejecutar Clang-Tidy
        run: pio check --skip-packages --tool clangtidy

  build-analysis:
    name: Construir y Compilar Proyecto
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: "x64"

      - name: Instalar PlatformIO
        run: pip install platformio

      - name: Compilar proyecto
        run: pio run

  run-tests:
    name: Ejecutar Pruebas
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: "x64"

      - name: Instalar PlatformIO
        run: pip install platformio

      - name: Ejecutar Pruebas Unitarias
        run: platformio test --environment esp32thing -f unit -v > result.log; tail -n 20 result.log

  logging-and-monitoring:
    name: Registro y Monitoreo de Build
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: "x64"

      - name: Instalar PlatformIO
        run: pip install platformio

      - name: Generar logs del proceso de build
        run: pio run -v > build_log.txt
    
