name: PlatformIO CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  platformio-ci:
    name: Pipeline PlatformIO
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar PlatformIO
        run: pip install platformio pip-audit

      - name: Comprobar dependencias desactualizadas
        run: pio pkg outdated
      
      - name: Actualizar setuptools
        run: pip install --upgrade setuptools

      - name: Auditar
        run: pip-audit

      - name: Compilar con PlatformIO (generar .cpp para Cppcheck)
        run: pio run --environment esp32thing

      - name: Ejecutar Cppcheck en el entorno
        run: cppcheck --enable=all --error-exitcode=0 src/ || true

      - name: Aplicar correcciones automáticas con Clang-Tidy
        run: pio check --environment esp32thing --skip-packages --flags="--fix-errors --system-headers" || true
