name: Sonarqube
on:
    push:
      branches:
        - main
        - src
        - 'releases/**'
    pull_request:
        types: [opened, synchronize, reopened]
  
jobs:
    sonarqube:
      name: Main Workflow
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
        with:
         fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0 # Ex: v4.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
            