name: Show Me the S3cr3tz
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
        DEFECTDOJO_ENGAGEMENT_ID: ${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}
        DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
      run: |
        echo ${{secrets.SONAR_TOKEN}} | sed 's/./& /g'